### ISSUE TITLE
Wiki - `React 캘린더 컴포넌트 개발 세부사항` 이미지 링크 오류

### ISSUE THREAD

**Issue by kyoungsik-dev** [D2CampusFest/6th#1]
**Wiki - `React 캘린더 컴포넌트 개발 세부사항` 이미지 링크 오류**

- 문서 내 이미지들이 모두 **cal1.png**로 되어있어 동일한 이미지가 반복됩니다.

**Comment by Kang-heesuk** [comment]
@kyoungsik-dev 확인하고 수정 마쳤습니다 :)
리포트 감사합니다!
