### ISSUE TITLE
★ [공지] 마지막 밋업 - 취소되었습니다.

### ISSUE THREAD

**Issue by Kang-heesuk** [D2CampusFest/6th#10]
참가신청 인원 저조로 인해 마지막 밋업은 취소되었습니다. 양해 부탁드립니다.

~~2월 21일(목) D2 StartupFactory에서 마지막 밋업이 진행됩니다.~~
~~※ 참여를 원하시는 분은 "팀명과 참가자 이름을 댓글"로 남겨주세요!~~

~~참가자 개별 프로젝트 진행과 다른 참가자들과 교류를 위해 만들어진 시간입니다.~~
~~오셔서 다른 참가자와 오프라인으로 논의도 하며, 팀의 이슈를 함께 해결해 볼 수 있어요!~~

~~일시 : 2월 21일(목), 오후 2시 - 7시 (1시 30분부터 입장가능)~~
~~장소 : 강남역 메리츠 타워 16층 D2 Startup Factory (위치보기)~~
~~★1층 오른쪽 출입구에서 16층 간다고 말해주시면 열어주실꺼에요!!★~~

~~오후 2시 - 5시 : 자유롭게 프로젝트 개발 및 토론 (개발자 Café처럼)~~
~~오후 5시 - 7시 : Tech Talk (w/ pizza party)~~
~~Tech Talk 발표를 원하시는 분들도 댓글로 알려주세요 :)~~
~~(*발표는 5~20분 정도로 희망자 수에 따라 시간은 조절될 수 있습니다.)~~

**Comment by xxxnell** [comment]
Chain 팀 두 명 참석합니다.

**Comment by xxxnell** [comment]
Chain팀 두 명 참석하겠습니다~ 
4시 30분 쯤에 도착할 예정입니다

**Comment by hubaimaster** [comment]
aws-interface 팀 김창환 참석하겠습니다!

**Comment by tucan9389** [comment]
iOS-Projects-with-ML-Models팀 곽도영 참석합니다!

**Comment by Kang-heesuk** [comment]
금주 밋업 참가자가 10명 이하인 경우 취소될 수 있음을 미리 양해부탁드립니다.
취소될 경우 별도로 연락드릴께요~

@xxxnell @hubaimaster @tucan9389

**Comment by DongDongKim** [comment]
React-Calenpicker 김동현 참석합니다

**Comment by azxca1731** [comment]
React-Calenpicker 이정훈 참석합니다!
개근상이 목표입니다 ㅎㅎ!

**Comment by hongjisung** [comment]
DataStructure 홍지성 참석합니다

**Comment by Kang-heesuk** [comment]
@xxxnell @hubaimaster @tucan9389 @DongDongKim @azxca1731 @hongjisung 
마지막 밋업은 참가신청 인원이 많지 않아 운영이 어려운 것으로 결정되었습니다.
이점 참고 부탁드리며 마지막 밋업에 참석신청해주셔서 감사드립니다.
그럼 결승전에서 바로 뵐께요~~
