### ISSUE TITLE
결승전 발표자료를 취합합니다! 

### ISSUE THREAD

**Issue by Kang-heesuk** [D2CampusFest/6th#11]
24일(일) 23:59까지 발표자료를 댓글로 남겨주세요!
- 행사장에서는 참가자 노트북의 wifi 사용이 불가합니다. (인터넷 가능한 공용 노트북 Mac, Windows 로 발표진행)

1. 영상을 준비하신 경우 URL도 함께 남겨주세요. (현장의 네트워크 문제로 인해 데모가 필요한 경우 미리 영상으로 준비하시는 것을 추천드립니다.)
2. 폰트 깨짐 등을 방지 하기 위해 발표자료는 pdf 형식으로 제출부탁드립니다.
(애니메이션 등이 필요한 경우에는 다른 형식으로 업로드 하셔도 무방합니다.)

파일용량 등의 제한이 있는 경우에는 slideshare 등의 url을 공유해주시거나 naver_d2@naver.com 으로 전달부탁드립니다.

**Comment by KangGilHwan** [comment]
Boggler팀 발표자료입니다!
[Boggler발표자료.pdf](https://github.com/D2CampusFest/6th/files/2894369/Boggler.pdf)
[Boggler발표자료.pptx](https://github.com/D2CampusFest/6th/files/2894370/Boggler.pptx)
[Demo 영상](https://www.youtube.com/watch?v=Hin_oocK4Kc&feature=youtu.be)

**Comment by KSAlpha** [comment]
Soma 팀 발표 자료 업로드합니다. (@Qwaz)

팀원 모두가 결승 일정에 참석이 어려운 관계로 (학업 관련 해외 일정, 대학원 개강), 발표를 영상으로 대체합니다.

[발표 자료](https://github.com/D2CampusFest/6th/files/2897695/soma.pdf)
[발표 영상](https://drive.google.com/file/d/1xlqEV1KajFKlv__4XQJPwhvf5tSdHXyF/view?usp=sharing)

**Comment by tucan9389** [comment]
iOS-Projects-with-ML-Models 팀 발표자료와 데모를 메일로 제출했습니다. 감사합니다.

**Comment by jaemin93** [comment]
Similar Pictures 팀 발표 자료 입니다.
[발표 자료](https://sway.office.com/n76GYJmuMhTdYFmk?ref=Link)
[발표 영상](https://drive.google.com/open?id=1OH23VmfkA405ghgK9_JsQTxJBKFjhL3n)

**Comment by hsi1032** [comment]
image_clustering팀 발표 자료입니다.
감사합니다.
[image_clustering_final.pdf](https://github.com/D2CampusFest/6th/files/2897806/image_clustering_final.pdf)

**Comment by hongjisung** [comment]
DataStructure 팀 발표자료입니다.
[발표자료](https://docs.google.com/presentation/d/1i-iWgGL0MgpboJqxeBJG_9IybecnkS-iQu9q60z_zyM/edit?usp=sharing)  파일->다른이름으로다운로드->pdf문서  
[발표영상](https://youtu.be/NBj8Nm8CRI8)

**Comment by lukepark327** [comment]
educhain 팀입니다. 발표자료 메일로 제출하였습니다.

**Comment by rhdtl78** [comment]
React-Calenpicker 팀입니다. 발표자료 메일로 제출하였습니다.

**Comment by xxxnell** [comment]
Chain 팀 발표자료 및 영상 메일로 제출했습니다.

**Comment by y0c** [comment]
react-datepicker 팀 발표자료 및 영상 메일로 제출했습니다.

**Comment by itsnamgyu** [comment]
AWS 인터페이스 팀 발표자료 메일로 제출했습니다!

**Comment by wnsgml972** [comment]
MPSec 팀 발표자료 및 영상 메일로 제출했습니다.

**Comment by sunnys-lab** [comment]
2019-D2CF 팀 발표자료 제출합니다.
원본 PPT 파일은 메일로 제출했습니다.
첨부된 파일은 다른이름으로 저장된 PDF 파일 입니다.
[2019-D2CF_final.pdf](https://github.com/D2CampusFest/6th/files/2897992/2019-D2CF_final.pdf)

**Comment by sangw0804** [comment]
data_structure_JS팀 발표자료 메일로 제출했습니다.

**Comment by Kang-heesuk** [comment]
모든 팀 발표자료 확인했습니다 :) 모두 고생많으셨어요~ 수요일에 뵐께요!
