### ISSUE TITLE
★ [공지] 첫 번째 밋업 참가 신청 (1월 23일-수)

### ISSUE THREAD

**Issue by Kang-heesuk** [D2CampusFest/6th#4]
1월 23일(수) D2 StartupFactory에서 첫 번째 밋업이 진행됩니다.
※ 첫 번째 밋업에 참여를 원하시는 분은 댓글 남겨주세요!

참가자 개별 프로젝트 진행과 다른 참가자들과 교류를 위해 만들어진 시간입니다.
오셔서 다른 참가자와 오프라인으로 논의도 하며, 팀의 이슈를 함께 해결해 볼 수 있어요!

일시 : 1월 23일(수), 오후 2시 - 7시 (1시 30분부터 입장가능)
장소 : 강남역 메리츠 타워 16층 D2 Startup Factory ([위치보기](https://map.naver.com/local/siteview.nhn?code=36797269))
★1층 오른쪽 출입구에서 16층 간다고 말해주시면 열어주실꺼에요!!★
* 오후 2시 - 5시 : 자유롭게 프로젝트 개발 및 토론 (개발자 Café처럼)
* 오후 5시 - 7시 : Tech Talk (w/ pizza party)

Tech Talk 발표를 원하시는 분들도 댓글로 알려주세요 :)
(*발표는 5~20분 정도로 희망자 수에 따라 시간은 조절될 수 있습니다.)

**Comment by itsnamgyu** [comment]
참가하겠습니다@

**Comment by tucan9389** [comment]
iOS-Projects-with-ML-Models팀 - 곽도영 참가합니다! 발표도 희망합니다 :-)

**Comment by azxca1731** [comment]
참가하겠습니다!

**Comment by haezu** [comment]
참가하겠습니다.

**Comment by jaemin93** [comment]
SimilarPictures팀 - 정재민, 김형일, 예해주 참가하겠습니다~!!

**Comment by KimHyungIlko** [comment]
참가하겠습니다~!

**Comment by xxxnell** [comment]
Chain팀 1명 참가하겠습니다

**Comment by sunnys-lab** [comment]
안녕하세요 지정과제팀 중 2019- 팀입니다. 혹시 해당일에 저녁 7시~9시 사이에 참가 및 장소를 이용 가능한지요?

**Comment by rayleighko** [comment]
Boggler - 고명진, 허지훈 등 2명 참가합니다!

**Comment by Kang-heesuk** [comment]
@sunnys-lab 안녕하세요, 저녁 7시부터 참석예정이라는 말씀인지요?
가급적 7시전에 오실 수 있다면 저희쪽에서 퇴실 안내 받으신 후 장소 이용하실수 있도록 하겠습니다.

**Comment by Kang-heesuk** [comment]
팀명도 적어주세요 캬캬캬
예시)  FEST팀 - 강희숙, 김도희 참가합니다!

**Comment by Kang-heesuk** [comment]
@tucan9389 우왕 발표신청 감사합니다!! 제목 정해지면 제목이 알려주세요~ 시간은 몇 분 정도 예상하시나요

**Comment by sunnys-lab** [comment]
> @sunnys-lab 안녕하세요, 저녁 7시부터 참석예정이라는 말씀인지요?
> 가급적 7시전에 오실 수 있다면 저희쪽에서 퇴실 안내 받으신 후 장소 이용하실수 있도록 하겠습니다.

감사합니다. 저녁 7시 전에 미리 도착할 수 있도록 하겠습니다.

**Comment by hubaimaster** [comment]
참석하겠습니다!

**Comment by tucan9389** [comment]
@Kang-heesuk 가볍게 공유하는 목적이니 5분~10분정도 생각합니다. 제목도 정해지면 댓글로 달겠습니다.

**Comment by y0c** [comment]
react-datepicker 팀 참가합니다!

**Comment by tucan9389** [comment]
@Kang-heesuk 발표자료 제목은 결국 못 정했습니다. ㅎㅎ 1주일동안 했던 내용과 앞으로 할 내용을 정리한거라 그냥 가벼운 수다처럼 듣고 흘리면 되는 발표가 될거 같습니다 :) 
발표자료는 [링크](https://docs.google.com/presentation/d/1UyOPwraNDa3Pmi6rVu_wh-2OTR4DpapuH963eXdK5ic/edit?usp=sharing)에 첨부해두었습니다.
