### ISSUE TITLE
★ [공지] 두 번째 밋업 참가 신청 (1월 29일-화)

### ISSUE THREAD

**Issue by Kang-heesuk** [D2CampusFest/6th#7]
1월 29일(화) D2 StartupFactory에서 두 번째 밋업이 진행됩니다.
※ 참여를 원하시는 분은 "팀명과 참가자 이름을 댓글"로 남겨주세요!

참가자 개별 프로젝트 진행과 다른 참가자들과 교류를 위해 만들어진 시간입니다.
오셔서 다른 참가자와 오프라인으로 논의도 하며, 팀의 이슈를 함께 해결해 볼 수 있어요!

일시 : 1월 29일(화), 오후 2시 - 7시 (1시 30분부터 입장가능)
장소 : 강남역 메리츠 타워 16층 D2 Startup Factory ([위치보기](https://map.naver.com/local/siteview.nhn?code=36797269))
★1층 오른쪽 출입구에서 16층 간다고 말해주시면 열어주실꺼에요!!★
* 오후 2시 - 5시 : 자유롭게 프로젝트 개발 및 토론 (개발자 Café처럼)
* 오후 5시 - 7시 : Tech Talk (w/ pizza party)

Tech Talk 발표를 원하시는 분들도 댓글로 알려주세요 :)
(*발표는 5~20분 정도로 희망자 수에 따라 시간은 조절될 수 있습니다.)

**Comment by azxca1731** [comment]
React-Calenpicker 이정훈 참여합니다!

**Comment by sangw0804** [comment]
data_structure_JS 오상우 참가합니다!

**Comment by tucan9389** [comment]
iOS-Projects-with-ML-Models 곽도영 참가합니다!

**Comment by hubaimaster** [comment]
aws-interface 김창환 참가합니다!

**Comment by jaemin93** [comment]
SimilarPictures 정재민 참가합니다!

**Comment by qwaz** [comment]
Soma 김강수, 배예찬 참가합니다

**Comment by rayleighko** [comment]
boggler - 강길환, 고명진, 허지훈 참가합니다!

**Comment by KimHyungIlko** [comment]
SimilarPictures 예해주 김형일 참석합니다!!

**Comment by DongDongKim** [comment]
React-Calenpicker 김동현 참여합니다!

**Comment by hongjisung** [comment]
DataStructure 홍지성 참가합니다
