### ISSUE TITLE
 ★ [공지] 세 번째 밋업 참가 신청 (2월 13일-수)

### ISSUE THREAD

**Issue by Kang-heesuk** [D2CampusFest/6th#8]
2월 13일(수) D2 StartupFactory에서 세 번째 밋업이 진행됩니다.
※ 참여를 원하시는 분은 "팀명과 참가자 이름을 댓글"로 남겨주세요!

참가자 개별 프로젝트 진행과 다른 참가자들과 교류를 위해 만들어진 시간입니다.
오셔서 다른 참가자와 오프라인으로 논의도 하며, 팀의 이슈를 함께 해결해 볼 수 있어요!

일시 : 2월 13일(수), 오후 2시 - 7시 (1시 30분부터 입장가능)
장소 : 강남역 메리츠 타워 16층 D2 Startup Factory (위치보기)
★1층 오른쪽 출입구에서 16층 간다고 말해주시면 열어주실꺼에요!!★

오후 2시 - 5시 : 자유롭게 프로젝트 개발 및 토론 (개발자 Café처럼)
오후 5시 - 7시 : Tech Talk (w/ pizza party)
Tech Talk 발표를 원하시는 분들도 댓글로 알려주세요 :)
(*발표는 5~20분 정도로 희망자 수에 따라 시간은 조절될 수 있습니다.)

**Comment by sunnys-lab** [comment]
2019팀 참석합니다.

**Comment by azxca1731** [comment]
React-Calenpicker 이정훈 참석합니다!

**Comment by itsnamgyu** [comment]
AWS-Interface 허남규 참석합니다!

**Comment by tucan9389** [comment]
iOS-Projects-with-ML-Models 곽도영 참석합니다!

**Comment by jaemin93** [comment]
SimilarPictures 팀 참석합니다!

**Comment by hubaimaster** [comment]
Aws-Interface 김창환 참석합니다!

**Comment by KSAlpha** [comment]
Soma 김강수, 배예찬 참가합니다

**Comment by geon0325** [comment]
image_clustering 팀 참석합니다.

**Comment by DongDongKim** [comment]
React-Calenpicker 김동현 참석합니다

**Comment by jaemin93** [comment]
Similar Pictures팀 Tech Talk 발표 신청합니다!

**Comment by Kang-heesuk** [comment]
@jaemin93 간단한 주제나 제목 알려주시면 타임테이블에 추가해놓을께요 :) 시간은 몇 분정도 예상하시나여

**Comment by hojihun5516** [comment]
보글러팀 허지훈 고명진 강길환 세명 참석합니다!

**Comment by sangw0804** [comment]
data_structure_JS 팀 오상우 참석합니다!

**Comment by jaemin93** [comment]
> @jaemin93 간단한 주제나 제목 알려주시면 타임테이블에 추가해놓을께요 :) 시간은 몇 분정도 예상하시나여

주제: 어떻게 하면 클러스터 개수를 잘 예측할 수 있을까? (10분 정도 예상)

**Comment by jaemin93** [comment]
> Similar Pictures팀 Tech Talk 발표 신청합니다!

발표 자료 입니다! (https://sway.office.com/ClnfNGarbrpzRezL?ref=Link)

**Comment by tucan9389** [comment]
iOS-Projects-with-ML-Models, 곽도영 tech talk 신청합니다.
제목: Just Point It
발표시간: 15분

**Comment by xxxnell** [comment]
@jaemin93 지금 발표 자료를 봤는데 Complexity때문에 곤란하다면 [Chinese restaurant process](https://en.wikipedia.org/wiki/Chinese_restaurant_process)가 도움이 될 수도 있을 것 같습니다.

**Comment by jaemin93** [comment]
@xxxnell 조언 감사합니다. 읽어보니 저희팀이 고민하던것을 완전히 짚어주는 것이군요!!ㅠㅠ 한번더 검토하고 회의한 후에 적용될수 있도록 하겠습니다 ^^ 감사해요!!
